apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
spec:
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: project
        image: moryarty/project:v0.1
