apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: project-svc
spec:
  type: ClusterIP
  selector:
    app: project
  ports:
  - name: http
    port: 2345
    protocol: TCP
    targetPort: 3000
