apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: shared-date
        emptyDir: {}
      containers:
      - name: time-output
        image: moryarty/time-output:v0.2
        volumeMounts:
        - name: shared-date
          mountPath: /usr/src/app/files
      - name: hash-output
        image: moryarty/hash-output:v0.2
        volumeMounts:
        - name: shared-date
          mountPath: /usr/src/app/files
